[workspace]
resolver = "2"
members = [
    "agent-uri",
    "agent-uri-attestation",
    "agent-uri-dht",
]

[workspace.package]
edition = "2024"
license = "MIT OR Apache-2.0"

[workspace.lints.rust]
unexpected_cfgs = { level = "warn", check-cfg = ['cfg(kani)'] }
